export { MaterialCard } from './components/MaterialCard'
export { MaterialGrid } from './components/MaterialGrid'
export { MaterialDetail } from './components/MaterialDetail'
export { SensoryMap } from './components/SensoryMap'
export { MaterialCompare } from './components/MaterialCompare'
export { Swatch } from './components/Swatch'
export { DuraBar } from './components/DuraBar'
export { useMaterials } from './hooks/useMaterials'
export { useCatalog } from './hooks/useCatalog'
export type { CatalogView } from './hooks/useCatalog'
